'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.subscribe': 'Subscribe',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'hero.title': 'Remove Watermark from Photo',
    'hero.subtitle': 'AI-Powered Watermark & Logo Remover',
    'hero.description': 'Remove watermarks and logos from your photos instantly with our advanced AI technology. Free, fast, and easy to use.',
    'hero.cta': 'Get Started Free',
    'hero.upload': 'Upload Photo',
    'features.title': 'Feature Highlights',
    'features.subtitle': 'Core capabilities that make watermark removal easy',
    'features.ai': 'AI-Powered',
    'features.ai.desc': 'Advanced artificial intelligence technology for precise watermark removal',
    'features.fast': 'Fast Processing',
    'features.fast.desc': 'Get results in seconds, not minutes',
    'features.quality': 'High Quality',
    'features.quality.desc': 'Maintain original image quality after removal',
    'features.easy': 'Easy to Use',
    'features.easy.desc': 'Simple interface, no technical skills required',
    'how.title': 'How It Works',
    'how.step1': 'Upload Your Photo',
    'how.step1.desc': 'Select an image with watermark or logo',
    'how.step2': 'AI Processing',
    'how.step2.desc': 'Our AI automatically detects and removes watermarks',
    'how.step3': 'Download Result',
    'how.step3.desc': 'Get your clean image in seconds',
    'faq.title': 'Frequently Asked Questions',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.refund': 'Refund Policy',
    'footer.disclaimer': 'Disclaimer',
    'footer.copyright': 'Copyright Notice',
    'footer.legal': 'Legal Notice',
    'footer.ip': 'Intellectual Property',
    'footer.contact': 'Contact',
    'footer.address': 'Address',
    'footer.phone': 'Phone',
    'footer.email': 'Email',
    'footer.address.value': '130 Building, Longhua Avenue, Longhua District, Shenzhen',
    'footer.email.value': 'support@chdaoai.com',
    'subscribe.title': 'Choose Your Plan',
    'subscribe.subtitle': 'Select a subscription plan that fits your needs',
    'subscribe.mostPopular': 'Most Popular',
    'subscribe.month': '/month',
    'subscribe.credits': 'credits/month',
    'subscribe.subscribeNow': 'Subscribe Now',
    'subscribe.feature1': 'Remove watermarks',
    'subscribe.feature2': 'Remove logos',
    'subscribe.feature3': 'High quality results',
    'subscribe.feature4': 'Fast processing',
    'subscribe.feature5': 'Monthly subscription',
    'removeWatermark.title': 'Remove Watermark from Photo',
    'removeWatermark.availableCredits': 'Available Credits',
    'removeWatermark.subscribeNow': 'Subscribe Now',
    'removeWatermark.uploadImage': 'Upload Image',
    'removeWatermark.uploadHint': 'Click to upload or drag and drop',
    'removeWatermark.result': 'Result',
    'removeWatermark.processing': 'Processing...',
    'removeWatermark.downloadResult': 'Download Result',
    'removeWatermark.resultPlaceholder': 'Result will appear here',
    'removeWatermark.removeButton': 'Remove Watermark',
    'removeWatermark.selectImageError': 'Please select an image first',
    'removeWatermark.insufficientCredits': 'Insufficient credits. Please subscribe to get more credits.',
    'removeWatermark.selectedAreas': 'Selected areas',
    'removeWatermark.clickHint': 'Click on the image to select watermark areas, or drag to select a region',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your account, view orders, and track your credits',
    'profile.accountInfo': 'Account Info',
    'profile.email': 'Email',
    'profile.availableCredits': 'Available Credits',
    'profile.subscribe': 'Subscribe Now',
    'profile.myOrders': 'My Orders',
    'profile.noOrders': 'No orders yet',
    'profile.orderDate': 'Date',
    'profile.orderAmount': 'Amount',
    'profile.orderCredits': 'Credits',
    'profile.orderStatus': 'Status',
    'profile.myConversions': 'My Conversions',
    'profile.noConversions': 'No conversions yet',
    'profile.viewOriginal': 'View Original',
    'profile.viewResult': 'View Result',
    'profile.myCredits': 'My Credits History',
    'profile.noCredits': 'No credit history yet',
    'profile.creditDate': 'Date',
    'profile.creditType': 'Type',
    'profile.creditAmount': 'Amount',
    'profile.creditDescription': 'Description',
    'profile.creditEarned': 'Earned',
    'profile.creditSpent': 'Spent',
    'profile.creditInitial': 'Initial',
    'contact.title': 'Contact Us',
    'contact.subtitle': "Get in touch with us. We'd love to hear from you!",
    'contact.getInTouch': 'Get in Touch',
    'contact.sendMessage': 'Send us a Message',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.sendButton': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent successfully!',
    'contact.successMessage': "Thank you for your message. We'll get back to you soon.",
    'contact.sendAnother': 'Send another message',
    'contact.charCount': 'characters',
    'about.title': 'About Us',
    'about.welcome': 'Welcome to RemoveWatermark, your trusted partner for removing watermarks and logos from images. We leverage cutting-edge artificial intelligence technology to provide fast, accurate, and high-quality watermark removal services.',
    'about.mission': 'Our Mission',
    'about.missionText': "Our mission is to make professional-grade image editing accessible to everyone. Whether you're a photographer, designer, or just someone who wants to clean up their photos, we provide the tools you need to achieve perfect results.",
    'about.technology': 'Our Technology',
    'about.technologyText': 'We use advanced AI algorithms trained on millions of images to intelligently detect and remove watermarks while preserving the original image quality. Our technology ensures that your images look natural and professional after watermark removal.',
    'about.whyChoose': 'Why Choose Us',
    'about.reason1': 'AI-powered technology for precise results',
    'about.reason2': 'Fast processing - get results in seconds',
    'about.reason3': 'High-quality output - maintain original image quality',
    'about.reason4': 'Easy to use - no technical skills required',
    'about.reason5': 'Secure and private - your images are processed safely',
    'usecases.title': 'Case Studies',
    'usecases.subtitle': 'See how our tool helps users remove watermarks',
    'usecases.photography': 'Photography',
    'usecases.photography.desc': 'Remove watermarks from stock photos and personal images',
    'usecases.business': 'Business',
    'usecases.business.desc': 'Clean up logos and watermarks from marketing materials',
    'usecases.personal': 'Personal Use',
    'usecases.personal.desc': 'Remove unwanted watermarks from your personal photos',
    'faq.q1': 'How does watermark removal work?',
    'faq.a1': 'Our AI technology analyzes your image and intelligently removes watermarks while preserving the original image quality.',
    'faq.q2': 'Is it free to use?',
    'faq.a2': 'New users get 5 free credits. After that, you can subscribe to one of our affordable plans.',
    'faq.q3': 'What image formats are supported?',
    'faq.a3': 'We support all common image formats including JPG, PNG, WEBP, and more.',
    'faq.q4': 'How long does processing take?',
    'faq.a4': 'Most images are processed in seconds. Complex images may take up to a minute.',
    'faq.q5': 'Will my images be stored?',
    'faq.a5': 'Images are processed securely and automatically deleted after processing for your privacy.',
    'cta.title': 'Ready to Remove Watermarks?',
    'cta.subtitle': 'Start using our AI-powered tool today',
    'cta.subscribe': 'Subscribe Now',
    'profile.conversion': 'conversion',
    'profile.record': 'record',
    'login.title': 'Sign in to your account',
    'copyright.title': 'Copyright Notice',
    'copyright.ownership': 'Copyright Ownership',
    'copyright.ownershipText': 'All content on this website, including but not limited to text, graphics, logos, images, and software, is the property of RemoveWatermark and is protected by copyright laws.',
    'copyright.userContent': 'User Content',
    'copyright.userContentText': "You retain all rights to images you upload to our service. By using our service, you grant us a limited license to process your images solely for the purpose of providing the service.",
    'copyright.prohibited': 'Prohibited Uses',
    'copyright.prohibitedText': 'You may not:',
    'copyright.prohibited1': 'Reproduce, distribute, or display our copyrighted content without permission',
    'copyright.prohibited2': "Use our service to infringe on others' copyrights",
    'copyright.prohibited3': 'Remove watermarks from copyrighted material without authorization',
    'copyright.dmca': 'DMCA Policy',
    'copyright.dmcaText': 'If you believe that content on our website infringes your copyright, please contact us at',
    'copyright.dmcaText2': 'with a DMCA takedown notice.',
    'copyright.license': 'License to Use',
    'copyright.licenseText': 'We grant you a limited, non-exclusive, non-transferable license to access and use our service for personal or commercial purposes, subject to these terms and conditions.',
    'copyright.fairUse': 'Fair Use',
    'copyright.fairUseText': 'You may use our copyrighted content under fair use provisions for purposes such as criticism, comment, news reporting, teaching, scholarship, or research. However, commercial use requires our explicit permission.',
    'copyright.enforcement': 'Copyright Enforcement',
    'copyright.enforcementText': 'We actively monitor and enforce our copyright rights. Unauthorized use of our copyrighted material may result in legal action, including but not limited to injunctive relief and monetary damages.',
    'copyright.attribution': 'Attribution Requirements',
    'copyright.attributionText': 'When using our service or referencing our content, proper attribution is appreciated but not required for service usage. However, removing copyright notices or attribution from our materials is strictly prohibited.',
    'copyright.international': 'International Copyright',
    'copyright.internationalText': 'Our content is protected by copyright laws in multiple jurisdictions. We respect international copyright treaties and expect users to comply with applicable copyright laws in their respective countries.',
    'copyright.contact': 'Copyright Contact',
    'copyright.contactText': 'For copyright-related inquiries, licensing requests, or permission to use our content, please contact us at',
    'legal.registration': 'Business Registration',
    'legal.registrationText': 'ChDaoAI is a registered business entity. Our business registration details are available upon request for legitimate business purposes.',
    'legal.jurisdiction': 'Jurisdiction and Governing Law',
    'legal.jurisdictionText': 'This website and its services are governed by the laws of the jurisdiction in which our company is registered. Any legal disputes shall be resolved in the appropriate courts of that jurisdiction.',
    'legal.content': 'Content Accuracy',
    'legal.contentText': 'While we strive to ensure the accuracy of information on our website, we do not warrant that all information is complete, current, or error-free. Users should verify critical information independently.',
    'legal.modifications': 'Modifications to Service',
    'legal.modificationsText': 'We reserve the right to modify, suspend, or discontinue any aspect of our service at any time without prior notice. We are not liable for any consequences resulting from such modifications.',
    'legal.liabilityLimit': 'Limitation of Liability',
    'legal.liabilityLimitText': 'To the fullest extent permitted by law, we disclaim all warranties and limit our liability for any damages arising from the use of this website or our services.',
    'legal.dataProtection': 'Data Protection',
    'legal.dataProtectionText': 'We comply with applicable data protection laws. For detailed information about how we handle personal data, please refer to our Privacy Policy.',
    'legal.compliance': 'Compliance',
    'legal.complianceText': 'We are committed to operating in compliance with all applicable laws and regulations. If you believe we have violated any legal requirements, please contact us immediately.',
    'ip.patents': 'Patents',
    'ip.patentsText': 'Our AI algorithms and processing methods may be protected by patents or patent applications. Unauthorized use, reproduction, or reverse engineering of our patented technology is strictly prohibited.',
    'ip.tradeSecrets': 'Trade Secrets',
    'ip.tradeSecretsText': 'We maintain proprietary trade secrets related to our AI technology, algorithms, and business processes. These trade secrets are protected by law and are not disclosed to third parties.',
    'ip.license': 'License Grant',
    'ip.licenseText': 'By using our service, you are granted a limited, revocable, non-exclusive license to use our intellectual property solely for the purpose of accessing and using our service in accordance with our Terms of Service.',
    'ip.restrictions': 'License Restrictions',
    'ip.restrictionsText': 'You may not:',
    'ip.restrictions1': 'Copy, modify, or create derivative works of our intellectual property',
    'ip.restrictions2': 'Reverse engineer, decompile, or disassemble our technology',
    'ip.restrictions3': 'Remove or alter any proprietary notices or labels',
    'ip.restrictions4': 'Use our intellectual property for any purpose other than accessing our service',
    'ip.enforcement': 'Enforcement of Rights',
    'ip.enforcementText': 'We reserve the right to take legal action against any infringement of our intellectual property rights. This may include seeking injunctive relief, damages, and recovery of legal costs.',
    'ip.thirdPartyIP': 'Third-Party Intellectual Property',
    'ip.thirdPartyIPText': 'We respect the intellectual property rights of third parties. If you believe that our service infringes your intellectual property rights, please contact us with detailed information about the alleged infringement.',
    'contact.businessHours': 'Business Hours',
    'contact.businessHoursText': 'Our customer support team is available during the following hours:',
    'contact.hours': 'Monday - Friday: 9:00 AM - 6:00 PM (GMT+8)',
    'contact.response': 'Response Time',
    'contact.responseText': 'We aim to respond to all inquiries within 24-48 hours during business days. For urgent matters, please indicate "URGENT" in your message subject line.',
    'contact.faq': 'Frequently Asked Questions',
    'contact.faqText': 'Before contacting us, you may find answers to common questions in our FAQ section or documentation.',
    'contact.support': 'Support Channels',
    'contact.supportText': 'You can reach us through the following channels:',
    'contact.support1': 'Email: support@chdaoai.com (Recommended for detailed inquiries)',
    'contact.support2': 'Contact Form: Use the form on this page for general inquiries',
    'contact.support3': 'Response Time: We typically respond within 24-48 hours',
    'contact.technical': 'Technical Support',
    'contact.technicalText': 'For technical issues or bug reports, please include the following information:',
    'contact.technical1': 'Description of the issue',
    'contact.technical2': 'Steps to reproduce the problem',
    'contact.technical3': 'Screenshots or error messages (if applicable)',
    'contact.technical4': 'Your account email and browser information',
    'contact.feedback': 'Feedback and Suggestions',
    'contact.feedbackText': 'We welcome your feedback and suggestions for improving our service. Please use the contact form to share your thoughts with us.',
    'contact.partnership': 'Partnership and Business Inquiries',
    'contact.partnershipText': 'For partnership opportunities, business collaborations, or media inquiries, please contact us at',
    'contact.partnershipEmail': 'business@chdaoai.com',
    'disclaimer.title': 'Disclaimer',
    'disclaimer.service': 'Service Disclaimer',
    'disclaimer.serviceText': 'Our watermark removal service is provided "as is" without any warranties, expressed or implied. We do not guarantee that the service will meet your specific requirements or that it will be error-free, uninterrupted, or secure.',
    'disclaimer.legalUse': 'Legal Use Only',
    'disclaimer.legalUseText': 'You are solely responsible for ensuring that your use of our service complies with all applicable laws and regulations. We are not responsible for any misuse of our service or any consequences resulting from such misuse.',
    'disclaimer.copyright': 'Copyright and Intellectual Property',
    'disclaimer.copyrightText': 'You must have the legal right to remove watermarks from any images you upload. Removing watermarks from copyrighted material without authorization may violate copyright laws. We are not responsible for any copyright infringement resulting from your use of our service.',
    'disclaimer.liability': 'Limitation of Liability',
    'disclaimer.liabilityText': 'To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of our service.',
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last updated:',
    'terms.acceptance': '1. Acceptance of Terms',
    'terms.acceptanceText': 'By accessing and using our service, you accept and agree to be bound by these Terms of Service. If you do not agree, please do not use our service.',
    'terms.use': '2. Use of Service',
    'terms.useText': 'You agree to use our service only for lawful purposes and in accordance with these terms.',
    'refund.title': 'Refund Policy',
    'refund.eligibility': '1. Refund Eligibility',
    'refund.eligibilityText': 'We offer refunds for subscription payments within 30 days of purchase, provided that:',
    'refund.eligibility1': 'The refund request is made within 30 days of the original purchase',
    'refund.eligibility2': 'The service has not been used extensively (less than 10% of credits used)',
    'refund.eligibility3': 'The request is made in good faith',
    'refund.howTo': '2. How to Request a Refund',
    'refund.howToText': 'To request a refund, please contact us at',
    'refund.howToText2': 'with your order details and reason for the refund request.',
    'refund.processing': '3. Processing Time',
    'refund.processingText': 'Refunds are typically processed within 5-10 business days. The refund will be issued to the original payment method.',
    'refund.nonRefundable': '4. Non-Refundable Items',
    'refund.nonRefundableText': 'The following are not eligible for refunds:',
    'refund.nonRefundable1': 'Used credits or services',
    'refund.nonRefundable2': 'Subscriptions that have been active for more than 30 days',
    'refund.nonRefundable3': 'Services that have been used extensively',
    'legal.title': 'Legal Notice',
    'legal.company': 'Company Information',
    'legal.companyText': 'This website is operated by ChDaoAI. For any legal inquiries, please contact us at:',
    'legal.email': 'Email:',
    'legal.address': 'Address:',
    'legal.liability': 'Liability',
    'legal.liabilityText': 'We strive to provide accurate and up-to-date information. However, we make no representations or warranties about the accuracy, completeness, or suitability of the information on this website.',
    'legal.links': 'External Links',
    'legal.linksText': 'Our website may contain links to external websites. We are not responsible for the content or privacy practices of these external sites.',
    'ip.title': 'Intellectual Property',
    'ip.our': 'Our Intellectual Property',
    'ip.ourText': 'All intellectual property rights in our service, including but not limited to our AI algorithms, software, trademarks, and trade secrets, are owned by us and protected by applicable laws.',
    'ip.user': 'User Content',
    'ip.userText': 'You retain all intellectual property rights in images you upload. We do not claim ownership of your content. However, by using our service, you grant us a limited license to process your images for the purpose of providing the service.',
    'ip.thirdParty': 'Respect for Third-Party Rights',
    'ip.thirdPartyText': 'You must respect the intellectual property rights of others. Do not use our service to remove watermarks from copyrighted material without proper authorization.',
    'ip.trademarks': 'Trademarks',
    'ip.trademarksText': 'All trademarks, service marks, and trade names used on this website are the property of their respective owners.',
    'privacy.title': 'Privacy Policy',
    'privacy.intro': '1. Introduction',
    'privacy.introText': 'We respect your privacy and are committed to protecting your personal data. This privacy policy explains how we collect, use, and safeguard your information when you use our service.',
    'privacy.collect': '2. Information We Collect',
    'privacy.collectText': 'We collect the following types of information:',
    'privacy.collect1': 'Account information (email, name) when you register',
    'privacy.collect2': 'Images you upload for processing',
    'privacy.collect3': 'Usage data and analytics',
    'privacy.collect4': 'Payment information (processed securely through third-party providers)',
    'privacy.use': '3. How We Use Your Information',
    'privacy.useText': 'We use your information to:',
    'privacy.use1': 'Provide and improve our services',
    'privacy.use2': 'Process your image removal requests',
    'privacy.use3': 'Manage your account and subscriptions',
    'privacy.use4': 'Send you important service updates',
    'privacy.use5': 'Ensure security and prevent fraud',
    'privacy.security': '4. Data Security',
    'privacy.securityText': 'We implement industry-standard security measures to protect your data. Images are processed securely and automatically deleted after processing. We use encryption and secure protocols to safeguard your information.',
    'privacy.retention': '5. Data Retention',
    'privacy.retentionText': 'We retain your account information for as long as your account is active. Processed images are automatically deleted after processing. We may retain certain data for legal or regulatory purposes.',
    'privacy.rights': '6. Your Rights',
    'privacy.rightsText': 'You have the right to:',
    'privacy.rights1': 'Access your personal data',
    'privacy.rights2': 'Correct inaccurate data',
    'privacy.rights3': 'Request deletion of your data',
    'privacy.rights4': 'Object to processing of your data',
    'privacy.rights5': 'Data portability',
    'privacy.contact': '7. Contact Us',
    'privacy.contactText': 'If you have questions about this privacy policy, please contact us at:',
    'privacy.cookies': '8. Cookies and Tracking Technologies',
    'privacy.cookiesText': 'We use cookies and similar tracking technologies to track activity on our service and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier.',
    'privacy.cookiesTypes': 'Types of cookies we use:',
    'privacy.cookies1': 'Essential cookies: Required for the service to function properly',
    'privacy.cookies2': 'Analytics cookies: Help us understand how visitors interact with our service',
    'privacy.cookies3': 'Preference cookies: Remember your settings and preferences',
    'privacy.thirdParty': '9. Third-Party Services',
    'privacy.thirdPartyText': 'We may use third-party services for payment processing, analytics, and authentication. These services have their own privacy policies governing the use of your information.',
    'privacy.thirdPartyList': 'Third-party services we use include:',
    'privacy.thirdParty1': 'Payment processors (Creem) for subscription payments',
    'privacy.thirdParty2': 'Authentication providers (Supabase) for user authentication',
    'privacy.thirdParty3': 'Cloud storage (Tencent Cloud) for image processing',
    'privacy.international': '10. International Data Transfers',
    'privacy.internationalText': 'Your information may be transferred to and processed in countries other than your country of residence. We ensure appropriate safeguards are in place to protect your data in accordance with this privacy policy.',
    'privacy.children': '11. Children\'s Privacy',
    'privacy.childrenText': 'Our service is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us.',
    'privacy.changes': '12. Changes to This Privacy Policy',
    'privacy.changesText': 'We may update our privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page and updating the "Last updated" date. You are advised to review this privacy policy periodically for any changes.',
    'terms.serviceDesc': '2. Service Description',
    'terms.serviceDescText': 'Our service provides AI-powered watermark and logo removal from images. We offer subscription plans with different credit allocations. The service is provided on an "as is" basis and we reserve the right to modify or discontinue the service at any time.',
    'terms.subscription': '3. Subscriptions and Payments',
    'terms.subscriptionText': 'By subscribing to our service, you agree to pay the subscription fees as specified in your chosen plan. Subscriptions are billed monthly and automatically renew unless cancelled.',
    'terms.subscriptionDetails': 'Subscription details:',
    'terms.subscription1': 'Subscriptions automatically renew at the end of each billing cycle',
    'terms.subscription2': 'You can cancel your subscription at any time through your account settings',
    'terms.subscription3': 'Cancellation takes effect at the end of the current billing period',
    'terms.subscription4': 'No refunds are provided for the current billing period after cancellation',
    'terms.accounts': '4. User Accounts',
    'terms.accountsText': 'You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.',
    'terms.ip': '5. Intellectual Property',
    'terms.ipText': 'You retain ownership of images you upload. By using our service, you grant us a license to process your images for the purpose of providing the service.',
    'terms.prohibited': '6. Prohibited Uses',
    'terms.prohibitedText': 'You may not use our service to:',
    'terms.prohibited1': 'Remove watermarks from copyrighted material without authorization',
    'terms.prohibited2': 'Violate any laws or regulations',
    'terms.prohibited3': 'Infringe on intellectual property rights',
    'terms.prohibited4': 'Upload malicious or harmful content',
    'terms.serviceChanges': '7. Service Modifications',
    'terms.serviceChangesText': 'We reserve the right to modify, suspend, or discontinue any part of our service at any time, with or without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation of the service.',
    'terms.termination': '8. Termination',
    'terms.terminationText': 'We may terminate or suspend your account and access to the service immediately, without prior notice, for any reason, including breach of these Terms of Service.',
    'terms.terminationUser': 'You may terminate your account at any time by contacting us or using the account deletion feature in your account settings.',
    'terms.liability': '9. Limitation of Liability',
    'terms.liabilityText': 'We are not liable for any damages arising from your use of our service. Our service is provided "as is" without warranties of any kind.',
    'terms.warranties': '10. Warranties and Disclaimers',
    'terms.warrantiesText': 'The service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or completely secure.',
    'terms.indemnification': '11. Indemnification',
    'terms.indemnificationText': 'You agree to indemnify and hold harmless RemoveWatermark and its affiliates from any claims, damages, losses, liabilities, and expenses arising from your use of the service or violation of these terms.',
    'terms.disputes': '12. Dispute Resolution',
    'terms.disputesText': 'Any disputes arising from these terms or the service shall be resolved through binding arbitration in accordance with the rules of the arbitration association, except where prohibited by law.',
    'terms.governing': '13. Governing Law',
    'terms.governingText': 'These Terms of Service shall be governed by and construed in accordance with the laws of the jurisdiction in which our company is registered, without regard to its conflict of law provisions.',
    'terms.contact': '14. Contact Us',
    'terms.contactText': 'For questions about these terms, contact us at:',
    'refund.conditions': '1. Refund Conditions',
    'refund.conditionsText': 'Refunds are available under the following conditions:',
    'refund.conditions1': 'Refund request must be submitted within 30 days of the original purchase date',
    'refund.conditions2': 'Less than 10% of the purchased credits have been used',
    'refund.conditions3': 'The subscription has not been active for more than 30 days',
    'refund.conditions4': 'No violation of our Terms of Service has occurred',
    'refund.partial': '2. Partial Refunds',
    'refund.partialText': 'In cases where more than 10% but less than 50% of credits have been used, we may offer a partial refund at our discretion. The refund amount will be calculated based on the unused portion of the subscription.',
    'refund.method': '3. Refund Method',
    'refund.methodText': 'Refunds will be processed to the original payment method used for the purchase. Processing times may vary depending on your payment provider:',
    'refund.method1': 'Credit/Debit cards: 5-10 business days',
    'refund.method2': 'PayPal: 3-5 business days',
    'refund.method3': 'Other payment methods: 7-14 business days',
    'refund.disputes': '4. Refund Disputes',
    'refund.disputesText': 'If you are not satisfied with our refund decision, you may contact us to discuss your case. We will review each dispute on a case-by-case basis and make a fair determination.',
    'refund.exceptions': '5. Exceptions and Special Cases',
    'refund.exceptionsText': 'In certain circumstances, we may make exceptions to our standard refund policy:',
    'refund.exceptions1': 'Technical issues preventing service use that are not resolved within 48 hours',
    'refund.exceptions2': 'Duplicate charges due to system errors',
    'refund.exceptions3': 'Service unavailability for extended periods (more than 7 consecutive days)',
    'refund.cancellation': '6. Subscription Cancellation',
    'refund.cancellationText': 'Cancelling your subscription does not automatically entitle you to a refund. Refunds are only available if you meet the refund conditions outlined above. Upon cancellation, your subscription will remain active until the end of the current billing period.',
    'disclaimer.availability': 'Service Availability',
    'disclaimer.availabilityText': 'We strive to maintain continuous service availability, but we do not guarantee that our service will be available at all times. The service may be temporarily unavailable due to maintenance, updates, or unforeseen circumstances. We are not liable for any losses or damages resulting from service unavailability.',
    'disclaimer.accuracy': 'Result Accuracy',
    'disclaimer.accuracyText': 'While we use advanced AI technology to remove watermarks, we cannot guarantee 100% accuracy in all cases. The quality of results may vary depending on factors such as image quality, watermark complexity, and image characteristics. We are not responsible for unsatisfactory results.',
    'disclaimer.thirdParty': 'Third-Party Content and Services',
    'disclaimer.thirdPartyText': 'Our service may integrate with third-party services and content. We are not responsible for the availability, accuracy, or content of third-party services. Your use of third-party services is subject to their respective terms and conditions.',
    'disclaimer.technical': 'Technical Failures',
    'disclaimer.technicalText': 'We are not liable for any damages or losses resulting from technical failures, including but not limited to server crashes, data loss, network issues, or software bugs. While we implement robust security measures, we cannot guarantee absolute security.',
    'disclaimer.userContent': 'User-Generated Content',
    'disclaimer.userContentText': 'We are not responsible for the content of images uploaded by users. Users are solely responsible for ensuring they have the legal right to process their images and that their content does not violate any laws or third-party rights.',
    'disclaimer.medical': 'No Medical or Legal Advice',
    'disclaimer.medicalText': 'Our service is provided for image processing purposes only. We do not provide medical, legal, or professional advice. Any information provided through our service should not be construed as professional advice.',
    'disclaimer.force': 'Force Majeure',
    'disclaimer.forceText': 'We shall not be liable for any failure or delay in performance under these terms resulting from acts beyond our reasonable control, including natural disasters, war, terrorism, labor disputes, or government actions.',
  },
  zh: {
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.subscribe': '订阅',
    'nav.login': '登录',
    'nav.logout': '退出',
    'nav.profile': '个人中心',
    'hero.title': '图片去水印',
    'hero.subtitle': 'AI智能水印和Logo移除工具',
    'hero.description': '使用先进的AI技术，瞬间去除照片中的水印和Logo。免费、快速、易用。',
    'hero.cta': '免费开始',
    'hero.upload': '上传照片',
    'features.title': '功能区域',
    'features.subtitle': '核心能力，让去水印更简单',
    'features.ai': 'AI驱动',
    'features.ai.desc': '先进的人工智能技术，精确去除水印',
    'features.fast': '快速处理',
    'features.fast.desc': '秒级获得结果',
    'features.quality': '高质量',
    'features.quality.desc': '保持原始图片质量',
    'features.easy': '易于使用',
    'features.easy.desc': '简单界面，无需技术技能',
    'how.title': '如何使用',
    'how.step1': '上传照片',
    'how.step1.desc': '选择带有水印或Logo的图片',
    'how.step2': 'AI处理',
    'how.step2.desc': 'AI自动检测并移除水印',
    'how.step3': '下载结果',
    'how.step3.desc': '秒级获得干净图片',
    'faq.title': '常见问题',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.refund': '退款政策',
    'footer.disclaimer': '免责声明',
    'footer.copyright': '版权声明',
    'footer.legal': '法律声明',
    'footer.ip': '知识产权',
    'footer.contact': '联系方式',
    'footer.address': '地址',
    'footer.phone': '电话',
    'footer.email': '邮箱',
    'footer.address.value': '深圳市龙华区龙华大道130栋',
    'footer.email.value': 'support@chdaoai.com',
    'subscribe.title': '选择套餐',
    'subscribe.subtitle': '选择适合您需求的订阅套餐',
    'subscribe.mostPopular': '最受欢迎',
    'subscribe.month': '/月',
    'subscribe.credits': '积分/月',
    'subscribe.subscribeNow': '立即订阅',
    'subscribe.feature1': '✓ 去除水印',
    'subscribe.feature2': '✓ 去除Logo',
    'subscribe.feature3': '✓ 高质量结果',
    'subscribe.feature4': '✓ 快速处理',
    'subscribe.feature5': '✓ 月度订阅',
    'removeWatermark.title': '图片去水印',
    'removeWatermark.availableCredits': '可用积分',
    'removeWatermark.subscribeNow': '立即订阅',
    'removeWatermark.uploadImage': '上传图片',
    'removeWatermark.uploadHint': '点击上传或拖拽文件',
    'removeWatermark.result': '结果',
    'removeWatermark.processing': '处理中...',
    'removeWatermark.downloadResult': '下载结果',
    'removeWatermark.resultPlaceholder': '结果将显示在这里',
    'removeWatermark.removeButton': '去除水印',
    'removeWatermark.selectImageError': '请先选择图片',
    'removeWatermark.insufficientCredits': '积分不足。请订阅以获得更多积分。',
    'removeWatermark.selectedAreas': '已选择区域',
    'removeWatermark.clickHint': '点击图片选择水印区域，或拖拽选择区域',
    'profile.title': '个人中心',
    'profile.subtitle': '管理您的账户，查看订单和积分记录',
    'profile.accountInfo': '账户信息',
    'profile.email': '邮箱',
    'profile.availableCredits': '可用积分',
    'profile.subscribe': '立即订阅',
    'profile.myOrders': '我的订单',
    'profile.noOrders': '暂无订单',
    'profile.orderDate': '日期',
    'profile.orderAmount': '金额',
    'profile.orderCredits': '积分',
    'profile.orderStatus': '状态',
    'profile.myConversions': '我的转换记录',
    'profile.noConversions': '暂无转换记录',
    'profile.viewOriginal': '查看原图',
    'profile.viewResult': '查看结果',
    'profile.myCredits': '我的积分记录',
    'profile.noCredits': '暂无积分记录',
    'profile.creditDate': '日期',
    'profile.creditType': '类型',
    'profile.creditAmount': '数量',
    'profile.creditDescription': '描述',
    'profile.creditEarned': '获得',
    'profile.creditSpent': '使用',
    'profile.creditInitial': '初始',
    'contact.title': '联系我们',
    'contact.subtitle': '与我们取得联系。我们很乐意听到您的声音！',
    'contact.getInTouch': '联系方式',
    'contact.sendMessage': '给我们留言',
    'contact.name': '姓名',
    'contact.email': '邮箱',
    'contact.message': '留言内容',
    'contact.sendButton': '发送留言',
    'contact.sending': '发送中...',
    'contact.success': '留言发送成功！',
    'contact.successMessage': '感谢您的留言。我们会尽快回复您。',
    'contact.sendAnother': '再发一条留言',
    'contact.charCount': '字符',
    'about.title': '关于我们',
    'about.welcome': '欢迎来到RemoveWatermark，您值得信赖的图片去水印和Logo移除服务伙伴。我们利用前沿的人工智能技术，提供快速、准确、高质量的水印移除服务。',
    'about.mission': '我们的使命',
    'about.missionText': '我们的使命是让专业级图片编辑变得人人可用。无论您是摄影师、设计师，还是只想清理照片的普通用户，我们都为您提供实现完美效果所需的工具。',
    'about.technology': '我们的技术',
    'about.technologyText': '我们使用在数百万张图片上训练的先进AI算法，智能检测并移除水印，同时保持原始图片质量。我们的技术确保您的图片在水印移除后看起来自然且专业。',
    'about.whyChoose': '为什么选择我们',
    'about.reason1': 'AI驱动技术，精确结果',
    'about.reason2': '快速处理 - 秒级获得结果',
    'about.reason3': '高质量输出 - 保持原始图片质量',
    'about.reason4': '易于使用 - 无需技术技能',
    'about.reason5': '安全私密 - 您的图片安全处理',
    'usecases.title': '案例展示',
    'usecases.subtitle': '了解我们的工具如何帮助用户去除水印',
    'usecases.photography': '摄影',
    'usecases.photography.desc': '从素材照片和个人图片中去除水印',
    'usecases.business': '商业',
    'usecases.business.desc': '清理营销材料中的Logo和水印',
    'usecases.personal': '个人使用',
    'usecases.personal.desc': '从您的个人照片中去除不需要的水印',
    'faq.q1': '去水印是如何工作的？',
    'faq.a1': '我们的AI技术分析您的图片，智能去除水印，同时保持原始图片质量。',
    'faq.q2': '是免费使用的吗？',
    'faq.a2': '新用户获得5个免费积分。之后，您可以订阅我们的套餐。',
    'faq.q3': '支持哪些图片格式？',
    'faq.a3': '我们支持所有常见图片格式，包括JPG、PNG、WEBP等。',
    'faq.q4': '处理需要多长时间？',
    'faq.a4': '大多数图片在几秒钟内处理完成。复杂图片可能需要一分钟。',
    'faq.q5': '我的图片会被存储吗？',
    'faq.a5': '图片安全处理，处理完成后自动删除，保护您的隐私。',
    'cta.title': '准备去除水印了吗？',
    'cta.subtitle': '立即开始使用我们的AI工具',
    'cta.subscribe': '立即订阅',
    'profile.conversion': '转换',
    'profile.record': '记录',
    'login.title': '登录您的账户',
    'copyright.title': '版权声明',
    'copyright.ownership': '版权所有权',
    'copyright.ownershipText': '本网站的所有内容，包括但不限于文本、图形、徽标、图像和软件，均为RemoveWatermark的财产，受版权法保护。',
    'copyright.userContent': '用户内容',
    'copyright.userContentText': '您保留上传到我们服务的所有图片的权利。通过使用我们的服务，您授予我们有限的许可，仅用于提供服务的目的处理您的图片。',
    'copyright.prohibited': '禁止使用',
    'copyright.prohibitedText': '您不得：',
    'copyright.prohibited1': '未经许可复制、分发或展示我们的版权内容',
    'copyright.prohibited2': '使用我们的服务侵犯他人的版权',
    'copyright.prohibited3': '未经授权从受版权保护的材料中移除水印',
    'copyright.dmca': 'DMCA政策',
    'copyright.dmcaText': '如果您认为我们网站上的内容侵犯了您的版权，请通过',
    'copyright.dmcaText2': '联系我们，并提供DMCA删除通知。',
    'copyright.license': '使用许可',
    'copyright.licenseText': '我们授予您有限的、非排他性的、不可转让的许可，以访问和使用我们的服务用于个人或商业目的，但须遵守这些条款和条件。',
    'copyright.fairUse': '合理使用',
    'copyright.fairUseText': '您可以在合理使用条款下使用我们的版权内容，用于批评、评论、新闻报道、教学、学术或研究等目的。但是，商业使用需要我们的明确许可。',
    'copyright.enforcement': '版权执行',
    'copyright.enforcementText': '我们积极监控和执行我们的版权权利。未经授权使用我们的版权材料可能导致法律行动，包括但不限于禁令救济和金钱赔偿。',
    'copyright.attribution': '署名要求',
    'copyright.attributionText': '使用我们的服务或引用我们的内容时，适当的署名是值得赞赏的，但对于服务使用不是必需的。但是，严格禁止从我们的材料中删除版权声明或署名。',
    'copyright.international': '国际版权',
    'copyright.internationalText': '我们的内容受多个司法管辖区的版权法保护。我们尊重国际版权条约，并期望用户遵守各自国家的适用版权法。',
    'copyright.contact': '版权联系',
    'copyright.contactText': '有关版权相关的咨询、许可请求或使用我们内容的许可，请通过',
    'legal.registration': '商业注册',
    'legal.registrationText': 'ChDaoAI是一家注册的商业实体。我们的商业注册详细信息可根据合法商业目的的要求提供。',
    'legal.jurisdiction': '管辖权和适用法律',
    'legal.jurisdictionText': '本网站及其服务受我们公司注册所在司法管辖区的法律管辖。任何法律争议应在该司法管辖区的适当法院解决。',
    'legal.content': '内容准确性',
    'legal.contentText': '虽然我们努力确保网站上信息的准确性，但我们不保证所有信息都是完整、最新或无错误的。用户应独立验证关键信息。',
    'legal.modifications': '服务修改',
    'legal.modificationsText': '我们保留随时修改、暂停或停止我们服务的任何方面的权利，无需事先通知。我们不对因此类修改而产生的任何后果承担责任。',
    'legal.liabilityLimit': '责任限制',
    'legal.liabilityLimitText': '在法律允许的最大范围内，我们放弃所有保证，并限制我们对因使用本网站或我们的服务而产生的任何损害的责任。',
    'legal.dataProtection': '数据保护',
    'legal.dataProtectionText': '我们遵守适用的数据保护法律。有关我们如何处理个人数据的详细信息，请参阅我们的隐私政策。',
    'legal.compliance': '合规性',
    'legal.complianceText': '我们致力于遵守所有适用的法律法规。如果您认为我们违反了任何法律要求，请立即联系我们。',
    'ip.patents': '专利',
    'ip.patentsText': '我们的AI算法和处理方法可能受专利或专利申请保护。未经授权使用、复制或反向工程我们的专利技术是严格禁止的。',
    'ip.tradeSecrets': '商业秘密',
    'ip.tradeSecretsText': '我们维护与我们的AI技术、算法和业务流程相关的专有商业秘密。这些商业秘密受法律保护，不会向第三方披露。',
    'ip.license': '许可授予',
    'ip.licenseText': '通过使用我们的服务，您被授予有限的、可撤销的、非排他性的许可，仅用于根据我们的服务条款访问和使用我们的服务的目的使用我们的知识产权。',
    'ip.restrictions': '许可限制',
    'ip.restrictionsText': '您不得：',
    'ip.restrictions1': '复制、修改或创建我们知识产权的衍生作品',
    'ip.restrictions2': '反向工程、反编译或反汇编我们的技术',
    'ip.restrictions3': '删除或更改任何专有通知或标签',
    'ip.restrictions4': '将我们的知识产权用于访问我们服务以外的任何目的',
    'ip.enforcement': '权利执行',
    'ip.enforcementText': '我们保留对任何侵犯我们知识产权的行为采取法律行动的权利。这可能包括寻求禁令救济、损害赔偿和追回法律费用。',
    'ip.thirdPartyIP': '第三方知识产权',
    'ip.thirdPartyIPText': '我们尊重第三方的知识产权。如果您认为我们的服务侵犯了您的知识产权，请向我们提供有关涉嫌侵权的详细信息。',
    'contact.businessHours': '营业时间',
    'contact.businessHoursText': '我们的客户支持团队在以下时间提供服务：',
    'contact.hours': '周一至周五：上午9:00 - 下午6:00（GMT+8）',
    'contact.response': '响应时间',
    'contact.responseText': '我们致力于在工作日内24-48小时内回复所有咨询。对于紧急事项，请在消息主题行中注明"紧急"。',
    'contact.faq': '常见问题',
    'contact.faqText': '在联系我们之前，您可以在我们的常见问题部分或文档中找到常见问题的答案。',
    'contact.support': '支持渠道',
    'contact.supportText': '您可以通过以下渠道联系我们：',
    'contact.support1': '邮箱：support@chdaoai.com（推荐用于详细咨询）',
    'contact.support2': '联系表单：使用本页面的表单进行一般咨询',
    'contact.support3': '响应时间：我们通常在24-48小时内回复',
    'contact.technical': '技术支持',
    'contact.technicalText': '对于技术问题或错误报告，请包含以下信息：',
    'contact.technical1': '问题描述',
    'contact.technical2': '重现问题的步骤',
    'contact.technical3': '截图或错误消息（如适用）',
    'contact.technical4': '您的账户邮箱和浏览器信息',
    'contact.feedback': '反馈和建议',
    'contact.feedbackText': '我们欢迎您提供反馈和建议，以改进我们的服务。请使用联系表单与我们分享您的想法。',
    'contact.partnership': '合作和商业咨询',
    'contact.partnershipText': '对于合作机会、业务协作或媒体咨询，请通过',
    'contact.partnershipEmail': 'business@chdaoai.com',
    'disclaimer.title': '免责声明',
    'disclaimer.service': '服务免责声明',
    'disclaimer.serviceText': '我们的去水印服务按"现状"提供，不提供任何明示或暗示的保证。我们不保证服务将满足您的特定要求，也不保证服务无错误、不间断或安全。',
    'disclaimer.legalUse': '仅限合法使用',
    'disclaimer.legalUseText': '您有责任确保您使用我们的服务符合所有适用的法律法规。我们不对任何滥用我们服务的行为或由此产生的任何后果负责。',
    'disclaimer.copyright': '版权和知识产权',
    'disclaimer.copyrightText': '您必须拥有从您上传的任何图片中移除水印的合法权利。未经授权从受版权保护的材料中移除水印可能违反版权法。我们不对因您使用我们的服务而产生的任何版权侵权负责。',
    'disclaimer.liability': '责任限制',
    'disclaimer.liabilityText': '在法律允许的最大范围内，我们不对因您使用我们的服务而产生的任何间接、偶然、特殊、后果性或惩罚性损害承担责任。',
    'terms.title': '服务条款',
    'terms.lastUpdated': '最后更新：',
    'terms.acceptance': '1. 接受条款',
    'terms.acceptanceText': '通过访问和使用我们的服务，您接受并同意受这些服务条款的约束。如果您不同意，请不要使用我们的服务。',
    'terms.use': '2. 服务使用',
    'terms.useText': '您同意仅将我们的服务用于合法目的，并遵守这些条款。',
    'refund.title': '退款政策',
    'refund.eligibility': '1. 退款资格',
    'refund.eligibilityText': '我们为购买后30天内的订阅付款提供退款，前提是：',
    'refund.eligibility1': '退款请求在原始购买后30天内提出',
    'refund.eligibility2': '服务未大量使用（使用的积分少于10%）',
    'refund.eligibility3': '请求是出于善意',
    'refund.howTo': '2. 如何申请退款',
    'refund.howToText': '要申请退款，请通过',
    'refund.howToText2': '联系我们，并提供您的订单详情和退款原因。',
    'refund.processing': '3. 处理时间',
    'refund.processingText': '退款通常在5-10个工作日内处理。退款将退回到原始付款方式。',
    'refund.nonRefundable': '4. 不可退款项目',
    'refund.nonRefundableText': '以下项目不符合退款条件：',
    'refund.nonRefundable1': '已使用的积分或服务',
    'refund.nonRefundable2': '已激活超过30天的订阅',
    'refund.nonRefundable3': '已大量使用的服务',
    'legal.title': '法律声明',
    'legal.company': '公司信息',
    'legal.companyText': '本网站由ChDaoAI运营。如有任何法律咨询，请通过以下方式联系我们：',
    'legal.email': '邮箱：',
    'legal.address': '地址：',
    'legal.liability': '责任',
    'legal.liabilityText': '我们努力提供准确和最新的信息。但是，我们不对本网站上信息的准确性、完整性或适用性作任何陈述或保证。',
    'legal.links': '外部链接',
    'legal.linksText': '我们的网站可能包含指向外部网站的链接。我们不对这些外部网站的内容或隐私做法负责。',
    'ip.title': '知识产权',
    'ip.our': '我们的知识产权',
    'ip.ourText': '我们服务中的所有知识产权，包括但不限于我们的AI算法、软件、商标和商业秘密，均归我们所有，并受适用法律保护。',
    'ip.user': '用户内容',
    'ip.userText': '您保留上传图片的所有知识产权。我们不声称拥有您的内容。但是，通过使用我们的服务，您授予我们有限的许可，以处理您的图片以提供服务。',
    'ip.thirdParty': '尊重第三方权利',
    'ip.thirdPartyText': '您必须尊重他人的知识产权。不要使用我们的服务在未经适当授权的情况下从受版权保护的材料中移除水印。',
    'ip.trademarks': '商标',
    'ip.trademarksText': '本网站上使用的所有商标、服务标记和商号均归其各自所有者所有。',
    'privacy.title': '隐私政策',
    'privacy.intro': '1. 介绍',
    'privacy.introText': '我们尊重您的隐私，并致力于保护您的个人数据。本隐私政策解释了我们在您使用我们的服务时如何收集、使用和保护您的信息。',
    'privacy.collect': '2. 我们收集的信息',
    'privacy.collectText': '我们收集以下类型的信息：',
    'privacy.collect1': '注册时的账户信息（邮箱、姓名）',
    'privacy.collect2': '您上传用于处理的图片',
    'privacy.collect3': '使用数据和 analytics',
    'privacy.collect4': '支付信息（通过第三方提供商安全处理）',
    'privacy.use': '3. 我们如何使用您的信息',
    'privacy.useText': '我们使用您的信息来：',
    'privacy.use1': '提供和改进我们的服务',
    'privacy.use2': '处理您的图片移除请求',
    'privacy.use3': '管理您的账户和订阅',
    'privacy.use4': '向您发送重要的服务更新',
    'privacy.use5': '确保安全并防止欺诈',
    'privacy.security': '4. 数据安全',
    'privacy.securityText': '我们实施行业标准的安全措施来保护您的数据。图片安全处理，处理完成后自动删除。我们使用加密和安全协议来保护您的信息。',
    'privacy.retention': '5. 数据保留',
    'privacy.retentionText': '只要您的账户处于活动状态，我们就会保留您的账户信息。处理后的图片在处理完成后自动删除。我们可能出于法律或监管目的保留某些数据。',
    'privacy.rights': '6. 您的权利',
    'privacy.rightsText': '您有权：',
    'privacy.rights1': '访问您的个人数据',
    'privacy.rights2': '更正不准确的数据',
    'privacy.rights3': '请求删除您的数据',
    'privacy.rights4': '反对处理您的数据',
    'privacy.rights5': '数据可移植性',
    'privacy.contact': '7. 联系我们',
    'privacy.contactText': '如果您对本隐私政策有疑问，请通过以下方式联系我们：',
    'privacy.cookies': '8. Cookie和跟踪技术',
    'privacy.cookiesText': '我们使用Cookie和类似的跟踪技术来跟踪我们服务上的活动并保存某些信息。Cookie是包含少量数据的文件，可能包括匿名唯一标识符。',
    'privacy.cookiesTypes': '我们使用的Cookie类型：',
    'privacy.cookies1': '必要Cookie：服务正常运行所必需',
    'privacy.cookies2': '分析Cookie：帮助我们了解访问者如何与我们的服务交互',
    'privacy.cookies3': '偏好Cookie：记住您的设置和偏好',
    'privacy.thirdParty': '9. 第三方服务',
    'privacy.thirdPartyText': '我们可能使用第三方服务进行支付处理、分析和身份验证。这些服务有自己的隐私政策来管理您信息的使用。',
    'privacy.thirdPartyList': '我们使用的第三方服务包括：',
    'privacy.thirdParty1': '支付处理商（Creem）用于订阅支付',
    'privacy.thirdParty2': '身份验证提供商（Supabase）用于用户身份验证',
    'privacy.thirdParty3': '云存储（腾讯云）用于图像处理',
    'privacy.international': '10. 国际数据传输',
    'privacy.internationalText': '您的信息可能会被传输到您居住国以外的国家并在那里处理。我们确保采取适当的保障措施，根据本隐私政策保护您的数据。',
    'privacy.children': '11. 儿童隐私',
    'privacy.childrenText': '我们的服务不适用于13岁以下的儿童。我们不会故意收集13岁以下儿童的个人信息。如果您是父母或监护人，并认为您的孩子向我们提供了个人信息，请联系我们。',
    'privacy.changes': '12. 隐私政策的变更',
    'privacy.changesText': '我们可能会不时更新我们的隐私政策。我们将在本页面上发布新的隐私政策并更新"最后更新"日期，以通知您任何变更。建议您定期查看本隐私政策以了解任何变更。',
    'terms.serviceDesc': '2. 服务描述',
    'terms.serviceDescText': '我们的服务提供AI驱动的图像水印和Logo移除功能。我们提供具有不同积分分配的订阅计划。服务按"现状"提供，我们保留随时修改或停止服务的权利。',
    'terms.subscription': '3. 订阅和付款',
    'terms.subscriptionText': '通过订阅我们的服务，您同意按照所选计划中指定的订阅费用付款。订阅按月计费，除非取消，否则会自动续订。',
    'terms.subscriptionDetails': '订阅详情：',
    'terms.subscription1': '订阅在每个计费周期结束时自动续订',
    'terms.subscription2': '您可以随时通过账户设置取消订阅',
    'terms.subscription3': '取消在当前计费周期结束时生效',
    'terms.subscription4': '取消后，当前计费周期不提供退款',
    'terms.accounts': '4. 用户账户',
    'terms.accountsText': '您有责任维护账户凭据的机密性。您同意在发现任何未经授权使用您的账户时立即通知我们。',
    'terms.ip': '5. 知识产权',
    'terms.ipText': '您保留上传图片的所有权。通过使用我们的服务，您授予我们处理您图片的许可，仅用于提供服务的目的。',
    'terms.prohibited': '6. 禁止使用',
    'terms.prohibitedText': '您不得使用我们的服务：',
    'terms.prohibited1': '未经授权从受版权保护的材料中移除水印',
    'terms.prohibited2': '违反任何法律法规',
    'terms.prohibited3': '侵犯知识产权',
    'terms.prohibited4': '上传恶意或有害内容',
    'terms.serviceChanges': '7. 服务修改',
    'terms.serviceChangesText': '我们保留随时修改、暂停或停止我们服务的任何部分的权利，无论是否通知。我们不对因服务的任何修改、暂停或停止而对您或任何第三方承担责任。',
    'terms.termination': '8. 终止',
    'terms.terminationText': '我们可能立即终止或暂停您的账户和服务访问，无需事先通知，原因包括违反本服务条款。',
    'terms.terminationUser': '您可以随时通过联系我们或使用账户设置中的账户删除功能来终止您的账户。',
    'terms.liability': '9. 责任限制',
    'terms.liabilityText': '我们不对因您使用我们的服务而产生的任何损害承担责任。我们的服务按"现状"提供，不提供任何形式的保证。',
    'terms.warranties': '10. 保证和免责声明',
    'terms.warrantiesText': '服务按"现状"和"可用"提供，不提供任何明示或暗示的保证。我们不保证服务将不间断、无错误或完全安全。',
    'terms.indemnification': '11. 赔偿',
    'terms.indemnificationText': '您同意赔偿并使RemoveWatermark及其关联公司免受因您使用服务或违反这些条款而产生的任何索赔、损害、损失、责任和费用。',
    'terms.disputes': '12. 争议解决',
    'terms.disputesText': '因这些条款或服务产生的任何争议应通过具有约束力的仲裁解决，按照仲裁协会的规则进行，法律禁止的情况除外。',
    'terms.governing': '13. 适用法律',
    'terms.governingText': '本服务条款应受我们公司注册所在司法管辖区的法律管辖并按其解释，不考虑其法律冲突条款。',
    'terms.contact': '14. 联系我们',
    'terms.contactText': '如有关于这些条款的问题，请通过以下方式联系我们：',
    'refund.conditions': '1. 退款条件',
    'refund.conditionsText': '在以下条件下可申请退款：',
    'refund.conditions1': '退款请求必须在原始购买日期后30天内提交',
    'refund.conditions2': '已使用的购买积分少于10%',
    'refund.conditions3': '订阅未激活超过30天',
    'refund.conditions4': '未发生违反我们服务条款的行为',
    'refund.partial': '2. 部分退款',
    'refund.partialText': '如果已使用超过10%但少于50%的积分，我们可能会酌情提供部分退款。退款金额将根据订阅的未使用部分计算。',
    'refund.method': '3. 退款方式',
    'refund.methodText': '退款将处理到用于购买的原始付款方式。处理时间可能因您的支付提供商而异：',
    'refund.method1': '信用卡/借记卡：5-10个工作日',
    'refund.method2': 'PayPal：3-5个工作日',
    'refund.method3': '其他支付方式：7-14个工作日',
    'refund.disputes': '4. 退款争议',
    'refund.disputesText': '如果您对我们的退款决定不满意，可以联系我们讨论您的案例。我们将逐案审查每个争议并做出公平的决定。',
    'refund.exceptions': '5. 例外和特殊情况',
    'refund.exceptionsText': '在某些情况下，我们可能会对我们的标准退款政策做出例外：',
    'refund.exceptions1': '在48小时内未解决的技术问题导致无法使用服务',
    'refund.exceptions2': '由于系统错误导致的重复收费',
    'refund.exceptions3': '服务长时间不可用（连续超过7天）',
    'refund.cancellation': '6. 订阅取消',
    'refund.cancellationText': '取消订阅并不自动使您有权获得退款。只有在您满足上述退款条件时才能获得退款。取消后，您的订阅将在当前计费周期结束前保持有效。',
    'disclaimer.availability': '服务可用性',
    'disclaimer.availabilityText': '我们努力保持服务的持续可用性，但不保证我们的服务将始终可用。由于维护、更新或不可预见的情况，服务可能会暂时不可用。我们不对因服务不可用而导致的任何损失或损害承担责任。',
    'disclaimer.accuracy': '结果准确性',
    'disclaimer.accuracyText': '虽然我们使用先进的AI技术来移除水印，但我们不能保证在所有情况下100%的准确性。结果质量可能因图像质量、水印复杂性和图像特征等因素而异。我们不对不满意的结果负责。',
    'disclaimer.thirdParty': '第三方内容和服务',
    'disclaimer.thirdPartyText': '我们的服务可能与第三方服务集成。我们不对第三方服务的可用性、准确性或内容负责。您对第三方服务的使用受其各自条款和条件的约束。',
    'disclaimer.technical': '技术故障',
    'disclaimer.technicalText': '我们不对因技术故障导致的任何损害或损失承担责任，包括但不限于服务器崩溃、数据丢失、网络问题或软件错误。虽然我们实施了强大的安全措施，但我们不能保证绝对安全。',
    'disclaimer.userContent': '用户生成的内容',
    'disclaimer.userContentText': '我们不对用户上传的图像内容负责。用户全权负责确保他们拥有处理其图像的合法权利，并且其内容不违反任何法律或第三方权利。',
    'disclaimer.medical': '无医疗或法律建议',
    'disclaimer.medicalText': '我们的服务仅用于图像处理目的。我们不提供医疗、法律或专业建议。通过我们的服务提供的任何信息不应被解释为专业建议。',
    'disclaimer.force': '不可抗力',
    'disclaimer.forceText': '对于因超出我们合理控制范围的行为而导致的本条款项下的任何履行失败或延迟，我们不承担责任，包括自然灾害、战争、恐怖主义、劳资纠纷或政府行为。',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved && (saved === 'en' || saved === 'zh')) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
